##########################################################################
######              lecture des valeurs du esmart3 via esphome 
#################################################################################


substitutions:
  #############################
  # comomon substitution #####
  ############################  
  name: esmart3v2-esp
  esphome_name: "esmart3v2-esp"
  friendly_name: "Esmart3v2-Esp"
  sensor_prefix: "esmart3"
  device_description: "Read Values from Esmart3 via RS485"
  time_timezone: "Europe/Paris"
  projectname: "Pat.Esmart3 Virtual Meter"
  appversion: 2.0.0
  log_level: "INFO"
  baud_rate: "0"
  api_encryption_key: !secret esmart3key
  ota_pswd: !secret esmart3ota
  ap_pwd: !secret esmart3ap
  adress_ip: !secret ip_esmart3
  gateway_ip: !secret ip_gateway
  dns_ip: !secret ip_dns
  
  ###########################
  ## LOCAL substitution #####
  ###########################
  tx_pin: GPIO1
  rx_pin: GPIO3
   
  
###############################
### definition de la carte ESP
###############################

esp32:
  board: esp32dev
  framework:
    type: arduino
###################################
### inclusion de la partie commune 
###################################

<<: !include .common.yaml

##################################
##  composants internes locaux ###
##################################
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome_components
    components: [ esmart3 ]

##################################################################
######################  programme principal ######################  
##################################################################

#########
# UART ##
#########
uart:
    id: uart_bus
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600
    

###########
# SENSORS #
###########

text_sensor:
  # IP address #
  - platform: wifi_info
    ip_address:
      name: "${sensor_prefix} IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "${sensor_prefix} Connected SSID"
    bssid:
      name: "${sensor_prefix} Connected BSSID"

  - platform: version
    id: text_sensor_version
    name: "${sensor_prefix} ESPHome Version"

sensor:
  - platform: wifi_signal
    name: "${sensor_prefix} WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    name: "${sensor_prefix} Uptime Sensor"
    update_interval: 60s

  - platform: esmart3
    charge_mode:
      id: charge_mode
      name: "${sensor_prefix} charge_mode"
    input_voltage:
      id: input_voltage
      name: "${sensor_prefix} input_voltage"
      unit_of_measurement: "V"
      state_class: total_increasing
      device_class: "voltage"
      accuracy_decimals: 1      
    battery_voltage:
      id: battery_voltage
      name: "${sensor_prefix} battery_voltage"
      unit_of_measurement: "V"
      state_class: total_increasing
      device_class: "voltage"
      accuracy_decimals: 1        
    charging_current:
      id: charging_current
      name: "${sensor_prefix} charging_current"
      unit_of_measurement: "A"
      state_class: total_increasing
      device_class: "current"
      accuracy_decimals: 1
    load_voltage:
      id: load_voltage
      name: "${sensor_prefix} load_voltage"
      unit_of_measurement: "V"
      state_class: total_increasing
      device_class: "voltage"
      accuracy_decimals: 1        
    load_current:
      id: load_current
      name: "${sensor_prefix} load_current"
      unit_of_measurement: "A"
      state_class: total_increasing
      device_class: "current"
      accuracy_decimals: 1      
    charging_power:
      id: charging_power
      name: "${sensor_prefix} charging_power"
      unit_of_measurement: "W"
      state_class: total_increasing
      device_class: "power"
      accuracy_decimals: 1      
    load_power:
      id: load_power
      name: "${sensor_prefix} load_power"
      unit_of_measurement: "W"
      state_class: total_increasing
      device_class: "power"
      accuracy_decimals: 1         
    battery_temp:
      id: battery_temp
      name: "${sensor_prefix} battery_temp"
      unit_of_measurement: "°C"
      state_class: total_increasing
      device_class: "temperature"
      accuracy_decimals: 1         
    internal_temp:
      id: internal_temp
      name: "${sensor_prefix} internal_temp"
      unit_of_measurement: "°C"
      state_class: total_increasing
      device_class: "temperature"
      accuracy_decimals: 1 
    battery_level:
      id: battery_level
      name: "${sensor_prefix} battery_level"
      unit_of_measurement: "%"
      state_class: total_increasing
      device_class: "battery"
      accuracy_decimals: 1   